namespace MAUIsland;

public partial class RadioButtonPageViewModel : NavigationAwareBaseViewModel
{
    #region [CTor]
    public RadioButtonPageViewModel(IAppNavigator appNavigator)
                                    : base(appNavigator)
    {

    }
    #endregion

    #region [Properties]

    [ObservableProperty]
    string codeExample1 = "<VerticalStackLayout>\r\n    <RadioButton Content=\"Cat\"\r\n         IsChecked=\"True\"/>\r\n    <RadioButton Content=\"Dog\"/>\r\n    <RadioButton Content=\"Fish/>\r\n    <RadioButton Content=\"Bird\"/>\r\n</VerticalStackLayout>";
    [ObservableProperty]
    string codeExample2 = "<VerticalStackLayout>\r\n    <VerticalStackLayout.Resources>\r\n        <FontImageSource x:Key= \"Happy\"\r\n                         Color=\"White\"\r\n                         FontFamily=\"{x:Static app:FontNames.FluentSystemIconsRegular}\"\r\n                         Glyph=\"{Static app:FluentUIIcon.Ic_fluent_emoji_28_regular}\"/>\r\n        <FontImageSource x:Key= \"Normal\"\r\n                         Color=\"White\"\r\n                         FontFamily=\"{x:Static app:FontNames.FluentSystemIconsRegular}\"\r\n                         Glyph=\"{Static app:FluentUIIcon.Ic_fluent_emoji_smile_slight_24_regular}\"/>\r\n        <FontImageSource x:Key=\"Sad\"\r\n                         Color=\"White\"\r\n                         FontFamily=\"{x:Static app:FontNames.FluentSystemIconsRegular}\"\r\n                         Glyph=\"{Static app:FluentUIIcon.Ic_fluent_emoji_sad_24_regular}\"/>\r\n    </VerticalStackLayout.Resources>\r\n    <RadioButton IsChecked=\"True\">\r\n        <RadioButton.Content>\r\n            <Image WidthRequest=\"30\" \r\n                   HorizontalOptions=\"Start\"\r\n                   VerticalOptions=\"Center\"\r\n                   Source=\"{x:StaticResource Happy}\"/>\r\n        </RadioButton.Content>\r\n    </RadioButton>\r\n    <RadioButton>\r\n        <RadioButton.Content>\r\n            <Image WidthRequest= \"30\" \r\n                   HorizontalOptions=\"Start\"\r\n                   VerticalOptions=\"Center\"\r\n                   Source=\"{x:StaticResource Normal}\"/>\r\n        </RadioButton.Content>\r\n    </RadioButton>\r\n    <RadioButton>\r\n        <RadioButton.Content>\r\n            <Image WidthRequest=\"30\" \r\n                   HorizontalOptions=\"Start\"\r\n                   VerticalOptions=\"Center\"\r\n                   Source=\"{x:StaticResource Sad}\"/>\r\n        </RadioButton.Content>\r\n    </RadioButton>\r\n</VerticalStackLayout>";
    [ObservableProperty]
    string codeExample3 = "<StackLayout Orientation=\"Horizontal\">\r\n    <StackLayout.Resources>\r\n        <FontImageSource x:Key= \"Happy\"\r\n                         Color=\"White\"\r\n                         FontFamily=\"{x:Static app:FontNames.FluentSystemIconsRegular}\"\r\n                         Glyph=\"{Static app:FluentUIIcon.Ic_fluent_emoji_28_regular}\"/>\r\n        <FontImageSource x:Key= \"Normal\"\r\n                         Color=\"White\"\r\n                         FontFamily=\"{x:Static app:FontNames.FluentSystemIconsRegular}\"\r\n                         Glyph=\"{Static app:FluentUIIcon.Ic_fluent_emoji_smile_slight_24_regular}\"/>\r\n        <FontImageSource x:Key=\"Sad\"\r\n                         Color=\"White\"\r\n                         FontFamily=\"{x:Static app:FontNames.FluentSystemIconsRegular}\"\r\n                         Glyph=\"{Static app:FluentUIIcon.Ic_fluent_emoji_sad_24_regular}\"/>\r\n    </StackLayout.Resources>\r\n    <RadioButton IsChecked=\"True\">\r\n        <RadioButton.Content>\r\n            <StackLayout>\r\n                <Image WidthRequest=\"30\" \r\n                   HorizontalOptions=\"Center\"\r\n                   VerticalOptions=\"Center\"\r\n                   Source=\"{x:StaticResource Happy}\"/>\r\n                <Label Text=\"Happy\" \r\n                       HorizontalOptions=\"Center\"\r\n                       VerticalOptions=\"End\"/>\r\n            </StackLayout>\r\n        </RadioButton.Content>\r\n    </RadioButton>\r\n    <RadioButton>\r\n        <RadioButton.Content>\r\n            <StackLayout>\r\n                <Image WidthRequest=\"30\" \r\n                   HorizontalOptions=\"Center\"\r\n                   VerticalOptions=\"Center\"\r\n                   Source=\"{x:StaticResource Normal}\"/>\r\n                <Label Text=\"Normal\" \r\n                       HorizontalOptions=\"Center\"\r\n                       VerticalOptions=\"End\"/>\r\n            </StackLayout>\r\n        </RadioButton.Content>\r\n    </RadioButton>\r\n    <RadioButton>\r\n        <RadioButton.Content>\r\n            <StackLayout>\r\n                <Image WidthRequest=\"30\" \r\n                   HorizontalOptions=\"Center\"\r\n                   VerticalOptions=\"Center\"\r\n                   Source=\"{x:StaticResource Sad}\"/>\r\n                <Label Text=\"Sad\" \r\n                       HorizontalOptions=\"Center\"\r\n                       VerticalOptions=\"End\"/>\r\n            </StackLayout>\r\n        </RadioButton.Content>\r\n    </RadioButton>\r\n</StackLayout>";
    #endregion

}
